### ISSUE TITLE
Demo: home screen header

### ISSUE THREAD

**Issue by anjali9265** [lumos-studio/leeway-website#100]
Implement the header section containing the logo and settings button. Refer to the screenshot.
<img width="300" alt="Screenshot 2023-06-18 at 19 30 22" src="https://github.com/zympl/leeway-website/assets/29055976/f7def964-71c5-4640-9f1d-f2f6eaf1f04d">

Design:
https://www.figma.com/file/rd8upWhFjqFRaX4hKTTOh3/leeway?type=design&node-id=1091-4390&t=aPSNVMiGbtDiXkhY-4

**Comment by Adhithyarajan** [comment]
Do i have to remove the previous shells created for doing this ?
