### ISSUE TITLE
Demo: home screen transaction list

### ISSUE THREAD

**Issue by anjali9265** [lumos-studio/leeway-website#102]
Implement the transaction list section. Refer to the screenshot.

<img width="300" alt="Screenshot 2023-06-18 at 19 36 06" src="https://github.com/zympl/leeway-website/assets/29055976/dca8fcbf-67ce-45a6-b977-fbd30eac5aee">

Design:
https://www.figma.com/file/rd8upWhFjqFRaX4hKTTOh3/leeway?type=design&node-id=1091-4390&t=aPSNVMiGbtDiXkhY-4

**Comment by Adhithyarajan** [comment]
Do i have to add the text inside these cards or the cards alone?

**Comment by ajayesivan** [comment]
> Do i have to add the text inside these cards or the cards alone?

Yes, you should add the texts, for now you can put some dummy data.

@Adhithyarajan Please mention the relevant members or the core team when asking questions about the issue otherwise we won't get notified.
